### ISSUE TITLE
Release scope for v1.0.0 

### ISSUE THREAD

**Issue by jeanduplessis** [crossplane-contrib/provider-kubernetes#213]
The following issues are planned for inclusion in the v1.0.0 release of this provider:

```[tasklist]
### Tasks
- [ ] https://github.com/crossplane-contrib/provider-kubernetes/issues/37
- [ ] https://github.com/crossplane-contrib/provider-kubernetes/issues/114
- [ ] https://github.com/crossplane-contrib/provider-kubernetes/issues/159
- [ ] https://github.com/crossplane-contrib/provider-kubernetes/issues/212
- [ ] https://github.com/crossplane-contrib/provider-kubernetes/issues/209
```

**Comment by jeanduplessis** [comment]
@bobh66 unfortunately not. It was a case of prioritizing the XPv2 work above other features in this provider. I'll discuss with maintainers what can be done to push these topics forward.
